name: GCP integration test push

on:
 workflow_dispatch:
 push:
    branches:
      - main
      - web-sync

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Set up Java
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: '17'
     - name: Set up sbt
       uses: sbt/setup-sbt@v1
     - name: Run unit tests
       run: sbt test package
     - name: Set up Databricks CLI
       uses: databricks/setup-cli@main
     - name: Deploy Databricks Asset Bundle
       env:
         DATABRICKS_HOST: https://416411475796958.8.gcp.databricks.com
         DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN_GCP }}
       run: databricks bundle deploy --target dev --auto-approve
